---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ printf "%s-egress-restrictions" (include "projectName" .) | quote }}
  namespace: {{ include "projectName" . | quote }}
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector: {}
    - ipBlock:
        cidr: '0.0.0.0/0'
        except: 
        - '10.0.0.0/8'
        - '172.16.0.0/12'
        - '192.168.0.0/16'
